### PR TITLE
Fix bug with basic authentication and at symbol in password in wsdl URL

### PR DESCRIPTION
**Pull request by philippe-granet**

### CODE REVIEW

**Comment by olensmar** [comment]
thanks - looks good to me!

**Comment by olensmar** [comment]
Hi Philippe - I'd love to merge this but need you to sign our CLA first - please see https://www.soapui.org/developers-corner/contribute-to-soapui.html for instructions!

Hope that works - great thanks for your help!

/Ole

**Comment by philippe-granet** [comment]
Envoyé de mon iPhone

**Comment by olensmar** [comment]
@philippe-granet ping!?

**Comment by philippe-granet** [comment]
2016-09-07 13:02 GMT+02:00 Ole Lensmar <notifications@github.com>:

**Comment by philippe-granet** [comment]
@olensmar 
[SmartBear Contributor License Agreement 041213.doc.pdf](https://github.com/SmartBear/soapui/files/483742/SmartBear.Contributor.License.Agreement.041213.doc.pdf)

**Comment by olensmar** [comment]
awesome - thank you!

**Pull request merged**
