### PR TITLE
SOAPUIOS-461-remove-context-menu-in-endpoint-explorer

### PR DESCRIPTION
**Pull request by ChristinaZelenko**
Checked context menu in Endpoint Explorer as unavailable
https://smartbear.atlassian.net/browse/SOAPUIOS-461

### CODE REVIEW

**Comment by antone-sb** [comment]
Will this keep context menu for test fields?

**Comment by AlexanderNikitin-Smartbear** [comment]
@antone-sb , do we need this fix in the release branch?

**Comment by antone-sb** [comment]
yes, @ChristinaZelenko please make this PR into release-5.5.0 branch.

**Comment by antone-sb** [comment]
What about my first question?

**Pull request closed without merging**
