### PR TITLE
passed in TestStep name should be used for TestStepConfig

### PR DESCRIPTION
**Pull request by hschott**
Without this fix a user is asked twice to enter a name for a new TestStep if the same TestStep type already exists in the TestCase.

### CODE REVIEW

**Comment by olensmar** [comment]
Hi! We'd love to merge this for our upcoming release - can you fix the merge conflict?

**Comment by prakashmrec** [comment]
@olensmar, @spindelmanne  This seems to be ready to be merged, if we have the contributor's agreement.

**Comment by olensmar** [comment]
@hschott sorry for the extreme delay here - looks like we need your CLA to merge this - see https://www.soapui.org/developers-corner/contribute-to-soapui.html - thanks!

**Comment by antone-sb** [comment]
@hschott We need your CLA to merge this - see https://www.soapui.org/developers-corner/contribute-to-soapui.html - thanks!

**Comment by antone-sb** [comment]
Created a JIRA ticket - https://smartbear.atlassian.net/browse/SOAPUIOS-362.

**Comment by IlyaAvdeev** [comment]
@hschott any updates on contributor agreement?

**Comment by IlyaAvdeev** [comment]
The issue is fixed by https://github.com/SmartBear/soapui/pull/370.

**Pull request closed without merging**
