### PR TITLE
SOAP-3908 Drop support for Java 6

### PR DESCRIPTION
**Pull request by spindelmanne**
We think the time has come to drop support for Java 6 in SoapUI OS.

When introducing the plugin framework we are using some Java 7 features already, and it'll be possible to write nicer code when we can use Java 7 constructs.

### CODE REVIEW

**Comment by spindelmanne** [comment]
@marcpa00 and @redfish4ktc , do you have any thoughts on this?

**Comment by marcpa00** [comment]
I’d say it’s time to drop it.

Marc

**Comment by spindelmanne** [comment]
Thanks, Marc!

**Comment by redfish4ktc** [comment]
+1 for me too as a dev and tools integrator

Java 7 has been used at runtime in SoapUI by end users for a while so this won't change anything for them

So let's go !

**Comment by spindelmanne** [comment]
Thank you for your input, Thomas!

**Comment by IlyaAvdeev** [comment]
Thanks everyone for your input

**Pull request merged**
