### PR TITLE
Changed com.jayway.jsonpath:json-path:0.9.1 to com.jayway.jsonpath:js…

### PR DESCRIPTION
**Pull request by Knesch**
Fix for issue https://github.com/SmartBear/soapui/issues/461

### CODE REVIEW

**Review by Aracaa — APPROVED** [review]

**Review by Aracaa — COMMENTED** [review]
The code seems OK and compilation is OK.

**Review by swapnil-git007 — COMMENTED** [review]
The changes are correct and approved.

**Comment by swapnil-git007** [comment]
Please merge these changes, it will make soapui more stronger.

**Comment by antone-sb** [comment]
@Knesch @FloOows @swapnil-git007 Thanks a lot for you contribution! We had to make another PR, as we changed a bit our pom structure.

**Pull request closed without merging**
