### PR TITLE
SOAPUIOS-161 Setting access for wsi test tools directory

### PR DESCRIPTION
**Pull request by IlyaAvdeev**
https://smartbear.atlassian.net/browse/SOAPUIOS-161

### CODE REVIEW

**Comment by spindelmanne** [comment]
The JIRA issue mentions modifying access, but the change is a change of file path. Could you explain?

**Comment by IlyaAvdeev** [comment]
I compared that path to R!A path and made those paths the same. (R!A doesn't have this problem)

**Comment by spindelmanne** [comment]
I suppose you've verified that this solves the problem?

**Comment by IlyaAvdeev** [comment]
works for Mac, didn't check with linux

**Comment by spindelmanne** [comment]
OK, I'll merge it, but don't forget to verify it on Linux too.

**Pull request merged**
